// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebaPuestoDGII.Data;

#nullable disable

namespace pruebaPuestoDGII.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240320002538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("pruebaPuestoDGII.Models.ComprobantesFiscales", b =>
                {
                    b.Property<string>("NCF")
                        .HasColumnType("TEXT");

                    b.Property<double>("Itbis18")
                        .HasColumnType("REAL");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<long>("RncCedula")
                        .HasColumnType("INTEGER");

                    b.HasKey("NCF");

                    b.ToTable("ComprobantesFiscales");

                    b.HasData(
                        new
                        {
                            NCF = "E310000000001",
                            Itbis18 = 36.0,
                            Monto = 200.0,
                            RncCedula = 98754321012L
                        },
                        new
                        {
                            NCF = "E310000000002",
                            Itbis18 = 180.0,
                            Monto = 1000.0,
                            RncCedula = 98754321012L
                        },
                        new
                        {
                            NCF = "E320000000001",
                            Itbis18 = 46.0,
                            Monto = 300.0,
                            RncCedula = 99754321012L
                        },
                        new
                        {
                            NCF = "E320000000002",
                            Itbis18 = 250.0,
                            Monto = 2000.0,
                            RncCedula = 99754321012L
                        },
                        new
                        {
                            NCF = "E330000000001",
                            Itbis18 = 80.0,
                            Monto = 100.0,
                            RncCedula = 99954321012L
                        },
                        new
                        {
                            NCF = "E330000000002",
                            Itbis18 = 120.0,
                            Monto = 500.0,
                            RncCedula = 99954321012L
                        },
                        new
                        {
                            NCF = "E340000000001",
                            Itbis18 = 90.0,
                            Monto = 350.0,
                            RncCedula = 99999321012L
                        },
                        new
                        {
                            NCF = "E340000000002",
                            Itbis18 = 110.0,
                            Monto = 800.0,
                            RncCedula = 99999321012L
                        });
                });

            modelBuilder.Entity("pruebaPuestoDGII.Models.Contribuyente", b =>
                {
                    b.Property<long>("RncCedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Contribuyente");

                    b.HasData(
                        new
                        {
                            RncCedula = 98754321012L,
                            Estatus = "inactivo",
                            Nombre = "JUAN PEREZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99754321012L,
                            Estatus = "inactivo",
                            Nombre = "PEDRO DURAN",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99954321012L,
                            Estatus = "activo",
                            Nombre = "JOSE SANTANA",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99999321012L,
                            Estatus = "inactivo",
                            Nombre = "GEORGE JIMENEZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99999921012L,
                            Estatus = "activo",
                            Nombre = "SOCRATES TAVAREZ",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99999999012L,
                            Estatus = "activo",
                            Nombre = "ALBERTO POLANCO",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            RncCedula = 99999999912L,
                            Estatus = "inactivo",
                            Nombre = "JULIAN RODRIGUEZ",
                            Tipo = "PERSONA FISICA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
