// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebaPuestoDGII.Data;

#nullable disable

namespace pruebaPuestoDGII.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240318223423_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("pruebaPuestoDGII.Models.ComprobantesFiscales", b =>
                {
                    b.Property<long>("RncCedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Itbis18")
                        .HasColumnType("REAL");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("ComprobantesFiscales");
                });

            modelBuilder.Entity("pruebaPuestoDGII.Models.Contribuyente", b =>
                {
                    b.Property<long>("RncCedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Contribuyente");
                });
#pragma warning restore 612, 618
        }
    }
}
